### ISSUE TITLE
Failed to obtain X-NP-GRANT-CODE error

### ISSUE THREAD

**Issue by EpicNation** [PassionDev/PSN-Bomber#2]
so i was testing it earlier and everything was working fine, after a few more tests i started to receive this error:

Warning: First parameter must either be an object or the name of an existing class in /var/www/html/PSN/include/auth.php on line 173
Failed to obtain X-NP-GRANT-CODE

Now it will not work at all whatsoever. 

What causes this error to pop up and how do i fix it and prevent it?

**Comment by PassionDev** [comment]
That means that your server ip is banned.

**Comment by EpicNation** [comment]
actually its not banned, its just a security feature that kicks in after you sent too many message requests, after a while it starts working again like normal

**Comment by PassionDev** [comment]
Strange, when i had that error my server ip was blocked from sending any requests.
